# Generated by Django 2.1.3 on 2018-11-19 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone', models.IntegerField(max_length=100, verbose_name='Phone Number')),
                ('state', models.CharField(max_length=200, verbose_name='State/Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
