# Generated by Django 2.1.3 on 2018-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181120_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=1337726887, unique=True, verbose_name='User ID'),
        ),
    ]
