# Generated by Django 2.1.3 on 2018-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=5940874559, unique=True, verbose_name='User ID'),
        ),
    ]
