# Generated by Django 2.1.3 on 2018-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181129_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=9126005628, unique=True, verbose_name='User ID'),
        ),
    ]
