# Generated by Django 2.1.3 on 2018-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181129_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=1926612848, unique=True, verbose_name='User ID'),
        ),
    ]
