# Generated by Django 2.1.3 on 2018-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181130_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=8186594655, unique=True, verbose_name='User ID'),
        ),
    ]
