# Generated by Django 2.1.3 on 2018-11-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181130_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.IntegerField(default=3350464529, unique=True, verbose_name='User ID'),
        ),
    ]
