# Generated by Django 2.1.3 on 2018-11-30 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181130_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='User_ID'),
        ),
    ]
