# Generated by Django 2.1.3 on 2018-11-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181130_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.UUIDField(default=93775068202, editable=False, unique=True, verbose_name='User_ID'),
        ),
    ]
