# Generated by Django 2.1.3 on 2018-11-30 01:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181130_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_no',
            field=models.UUIDField(default=users.models.random_id, editable=False, unique=True, verbose_name='User_ID'),
        ),
    ]
