# Generated by Django 2.1.3 on 2018-11-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181130_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='useraddress',
        ),
    ]
