# Generated by Django 2.1.3 on 2018-12-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20181207_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Transaction Fee')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='receivedpayment',
            name='info',
            field=models.CharField(default='No Payment Info', max_length=1000, null=True, verbose_name='Payment Details'),
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
