# Generated by Django 2.1.3 on 2018-12-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20181208_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentpayment',
            name='info',
            field=models.CharField(default='No Payment Info', max_length=1000, null=True, verbose_name='Payment Details'),
        ),
    ]
