# Generated by Django 2.1.3 on 2018-12-08 01:44

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_sentpayment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedpayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=19, verbose_name='Transaction Fee'),
        ),
        migrations.AddField(
            model_name='sentpayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=19, verbose_name='Transaction Fee'),
        ),
    ]
