# Generated by Django 2.1.3 on 2018-12-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20181208_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedpayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Transaction Fee'),
        ),
        migrations.AlterField(
            model_name='sentpayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Transaction Fee'),
        ),
    ]
