# Generated by Django 2.1.3 on 2018-12-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20181208_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
