# Generated by Django 2.1.3 on 2018-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20181220_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedpayment',
            name='receiver_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Receiver Balance'),
        ),
        migrations.AddField(
            model_name='receivedpayment',
            name='sender_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Sender Balance'),
        ),
        migrations.AddField(
            model_name='sentpayment',
            name='receiver_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Receiver Balance'),
        ),
        migrations.AddField(
            model_name='sentpayment',
            name='sender_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Sender Balance'),
        ),
    ]
