# Generated by Django 2.1.3 on 2018-12-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20181220_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedpayment',
            old_name='type',
            new_name='trans_type',
        ),
        migrations.RenameField(
            model_name='sentpayment',
            old_name='type',
            new_name='trans_type',
        ),
    ]
