# Generated by Django 2.1.3 on 2018-11-29 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_payment', models.BooleanField(default=True, verbose_name='Send Payments')),
                ('receive_payment', models.BooleanField(verbose_name='Receive Payment')),
                ('surveys', models.BooleanField(verbose_name='Surveys')),
                ('news', models.BooleanField(verbose_name='New and Promotions')),
                ('info_update', models.BooleanField(default=True, verbose_name='information Update')),
                ('address_update', models.BooleanField(verbose_name='Address Update')),
                ('bank_update', models.BooleanField(verbose_name='Bank Update')),
                ('card_update', models.BooleanField(verbose_name='Card Update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
