# Generated by Django 2.1.3 on 2018-11-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myaccount', '0002_auto_20181129_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.FloatField(verbose_name='Available Balance')),
                ('pending_balance', models.FloatField(verbose_name='Pending Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_payment',
            field=models.BooleanField(default=True, verbose_name='Send Payment'),
        ),
    ]
