# Generated by Django 2.1.3 on 2018-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20181130_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='pending_balance',
            field=models.FloatField(null=True, verbose_name='Pending Balance'),
        ),
    ]
