# Generated by Django 2.1.3 on 2018-11-30 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myaccount', '0004_auto_20181130_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField(verbose_name='Credit Card Number')),
                ('exp_date', models.CharField(max_length=10, verbose_name='Expiration Date')),
                ('card_type', models.CharField(choices=[('MC', 'MasterCard'), ('VS', 'Visa')], default='MC', max_length=2, verbose_name='Card Type')),
                ('security_code', models.IntegerField(verbose_name='Security Code')),
                ('billing_address', models.CharField(max_length=100, verbose_name='Billing Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Available Balance'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Pending Balance'),
        ),
    ]
