# Generated by Django 2.1.3 on 2018-11-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_auto_20181130_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cards',
            new_name='ccards',
        ),
    ]
