# Generated by Django 2.1.3 on 2018-11-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_auto_20181130_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='Billing Address'),
        ),
    ]
