# Generated by Django 2.1.3 on 2018-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20181130_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='pending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, verbose_name='Pending Balance'),
        ),
    ]
