# Generated by Django 2.1.3 on 2018-12-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0009_auto_20181202_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Available Balance'),
        ),
    ]
