# Generated by Django 2.1.3 on 2018-12-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0014_auto_20181207_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifiercount',
            old_name='count',
            new_name='counter',
        ),
    ]
