# Generated by Django 2.1.3 on 2018-12-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0015_auto_20181207_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiercount',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
