# Generated by Django 2.1.3 on 2018-12-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0016_auto_20181208_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
